language: java
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
branches:
  only:
    - master
    - 2020
notifications:
  email: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
install:
  - true
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
script:
  - |
    # publish the simulator to maven local
    ./gradlew :simulator:publishToMavenLocal --refresh-dependencies
    ./gradlew :simulator-ctre:publishToMavenLocal
    ./gradlew :simulator-rev:publishToMavenLocal

    # Clone the hacky repo, publish into it
    git clone --depth=50 --branch=master https://github.com/cpostbitbuckets/maven_repo.git ../../cpostbitbuckets/maven_repo
    mkdir -p ../../cpostbitbuckets/maven_repo/org/bitbuckets
    cp -rf ~/.m2/repository/org/bitbuckets/simulator ../../cpostbitbuckets/maven_repo/org/bitbuckets/
    cp -rf ~/.m2/repository/org/bitbuckets/simulator-ctre ../../cpostbitbuckets/maven_repo/org/bitbuckets/
    cp -rf ~/.m2/repository/org/bitbuckets/simulator-rev ../../cpostbitbuckets/maven_repo/org/bitbuckets/
deploy:
  - provider: script
    script: pwd; cd ../../cpostbitbuckets/maven_repo; pwd; ls; chmod +x commit_updates.sh; ./commit_updates.sh
    skip_cleanup: true
    on:
      all_branches: true
